export const TOPIC_LIST = 'TOPIC_LIST';
export const TOPIC_LIST_SUCCESS = 'TOPIC_LIST_SUCCESS';
export const MAIN_LIST = 'MAIN_LIST';
export const MAIN_LIST_SUCCESS = 'MAIN_LIST_SUCCESS';
export const WRITER_LIST = 'WRITER_LIST';
export const WRITER_LIST_SUCCESS = 'WRITER_LIST_SUCCESS';
